# delelopment
system:
  # 设定模式(debug/release/test,正式版改为release)
  mode: debug
  # url前缀
  url-path-prefix: api
  # 程序监听端口
  port: 8888
  # 是否初始化数据(没有初始数据时使用, 已发布正式版改为false)
  init-data: true
  # rsa公钥文件路径(config.yml相对路径, 也可以填绝对路径)
  rsa-public-key: bind-pub.pem
  # rsa私钥文件路径(config.yml相对路径, 也可以填绝对路径)
  rsa-private-key: bind-priv.pem

logs:
  log-config-str: '<seelog type="asynctimer" asyncinterval="1000" minlevel="trace" maxlevel="error">
  <outputs formatid="common">
  <buffered formatid="common" size="1048576" flushperiod="1000">
  <rollingfile type="size" filename="./log/cli.log" maxsize="104857600" maxrolls="10"/>
  </buffered>
  </outputs>
  <formats>
  <format id="common" format="%Date %Time [%LEV] [%File:%Line] [%Func] %Msg%n" />
  </formats>
  </seelog>'

mysql:
  # 用户名
  username: root
  # 密码
  password: root
  # 数据库名
  database: bind
  # 主机地址
  host: 127.0.0.1
#  host: localhost
  # 端口
  port: 3306
  # 连接字符串参数
  query: parseTime=True&loc=Local&timeout=10000ms
  # 是否打印日志
  log-mode: true
  # 数据库表前缀(无需再末尾添加下划线, 程序内部自动处理)
  table-prefix: tb
  # 编码方式
  charset: utf8mb4
  # 字符集(utf8mb4_general_ci速度比utf8mb4_unicode_ci快些)
  collation: utf8mb4_general_ci

# casbin配置
casbin:
  # 模型配置文件, config.yml相对路径
  model-path: 'rbac_model.conf'

# jwt配置
jwt:
  # jwt标识
  realm: test jwt
  # 服务端密钥
  key: secret key
  # token过期时间, 小时
  timeout: 12000
  # 刷新token最大过期时间, 小时
  max-refresh: 12000

# 令牌桶限流配置
rate-limit:
  # 填充一个令牌需要的时间间隔,毫秒
  fill-interval: 50
  # 桶容量
  capacity: 200
